http:
  routers:
    api-router:
      rule: 'Host(`{{ env "APP_DOMAIN" }}`) && PathPrefix(`/api/v1`)'
      service: api-service
      entryPoints:
        - web
      priority: 100
      middlewares:
        - cors-middleware@file

  services:
    api-service:
      loadBalancer:
        servers:
          # For docker, use: http://api:9000
          # For live update (run api with `pnpm dev`) , use: http://host.docker.internal:3000
          - url: "http://api:9000"