http:
  routers:
    admin-router:
      rule: 'Host(`{{ env "APP_DOMAIN" }}`) && PathPrefix(`/`) && !PathPrefix(`/api/v1`)'
      service: web
      entryPoints:
        - web
      priority: 100
      middlewares:
        - cors-middleware@file

  services:
    web:
      loadBalancer:
        servers:
          # For docker, use: http://nexpay-web:3000
          # For live update (run api with `pnpm dev`) , use: http://host.docker.internal:3000
          - url: "http://nexpay-web:9001"